# Generated by Django 3.2.7 on 2021-09-07 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210903_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.CharField(primary_key=True,default=uuid.uuid4, editable=False, max_length=36, serialize=False),
        ),
    ]
